#!/usr/bin/env node
/**
 * NinA AI — email template build script
 * ---------------------------------------------------------------
 * Usage:
 *   node build.js                          → compile MJML, emit
 *                                            dist/template.html and
 *                                            dist/template.js (editor)
 *   node build.js --data sample-data.json  → also merge sample data,
 *                                            writes dist/template-filled.html
 *   node build.js --minify                 → minify all HTML output
 *   node build.js --watch                  → re-build on save
 *                                            (combinable with --data /
 *                                            --minify)
 */

const fs = require('fs');
const path = require('path');
const mjml2html = require('mjml');
const Handlebars = require('handlebars');

Handlebars.registerHelper('add', (a, b) => Number(a) + Number(b));

// --- arg parsing ----------------------------------------------------
const args = process.argv.slice(2);
const dataIdx = args.indexOf('--data');
const dataFile = dataIdx !== -1 ? args[dataIdx + 1] : null;
const minify = args.includes('--minify');
const watch = args.includes('--watch');

// --- paths ----------------------------------------------------------
const ROOT = __dirname;
const SRC = path.join(ROOT, 'src', 'template.mjml');
const DIST_DIR = path.join(ROOT, 'dist');
const DIST_TPL = path.join(DIST_DIR, 'template.html');
const DIST_FILLED = path.join(DIST_DIR, 'template-filled.html');
const SAMPLE_PATH = path.join(ROOT, 'sample-data.json');

if (!fs.existsSync(SRC)) {
  console.error(`✗ MJML source not found at ${SRC}`);
  process.exit(1);
}
if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });

function build() {
  const t0 = Date.now();
  const mjmlSrc = fs.readFileSync(SRC, 'utf8');

  const compiled = mjml2html(mjmlSrc, {
    validationLevel: 'soft',
    minify,
    minifyOptions: { collapseWhitespace: true, removeComments: false },
    keepComments: false,
    fonts: {},
  });

  if (compiled.errors && compiled.errors.length) {
    for (const err of compiled.errors) {
      console.warn('[MJML]', err.formattedMessage || err.message);
    }
  }

  fs.writeFileSync(DIST_TPL, compiled.html, 'utf8');

  const sampleData = fs.existsSync(SAMPLE_PATH)
    ? JSON.parse(fs.readFileSync(SAMPLE_PATH, 'utf8'))
    : {};
  fs.writeFileSync(
    path.join(DIST_DIR, 'template.js'),
    '// AUTO-GENERATED by build.js — do not edit by hand.\n' +
      `window.NINA_EMAIL_TEMPLATE = ${JSON.stringify(compiled.html)};\n` +
      `window.NINA_SAMPLE_DATA = ${JSON.stringify(sampleData, null, 2)};\n`,
    'utf8',
  );

  let filledPath = null;
  if (dataFile) {
    const dataPath = path.resolve(process.cwd(), dataFile);
    if (!fs.existsSync(dataPath)) {
      console.error(`✗ Data file not found: ${dataPath}`);
      process.exit(1);
    }
    const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
    const tpl = Handlebars.compile(compiled.html);
    fs.writeFileSync(DIST_FILLED, tpl(data), 'utf8');
    filledPath = DIST_FILLED;
  }

  const ms = Date.now() - t0;
  const sizeKb = (Buffer.byteLength(compiled.html, 'utf8') / 1024).toFixed(1);
  console.log(
    `✓ Built in ${ms}ms · ${sizeKb} KB${minify ? ' (minified)' : ''}` +
    (filledPath ? ` · sample → ${path.relative(ROOT, filledPath)}` : ''),
  );
}

// --- run ------------------------------------------------------------
build();

if (watch) {
  console.log(`👀 Watching src/template.mjml and sample-data.json…`);
  const watchTargets = [SRC];
  if (fs.existsSync(SAMPLE_PATH)) watchTargets.push(SAMPLE_PATH);

  let pending = null;
  for (const target of watchTargets) {
    fs.watch(target, { persistent: true }, () => {
      // debounce — editors fire multiple events per save
      if (pending) clearTimeout(pending);
      pending = setTimeout(() => {
        try { build(); }
        catch (e) { console.error('✗ Build failed:', e.message); }
      }, 80);
    });
  }
}
